/**
 * Seed Platform Features to Firestore
 *
 * This script populates the platformFeatures collection with all available features.
 * Run with: node scripts/seedFeatures.js
 */

const admin = require('firebase-admin');
const serviceAccount = require('../firebase-service-account.json');

// Initialize Firebase Admin
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

const features = [
  // CORE BUSINESS FEATURES
  {
    featureId: 'invoice_creation',
    name: 'Invoice Creation',
    displayName: 'Invoice Creation',
    description: 'Allow merchants to create and manage invoices with multiple items',
    category: 'core_business',
    tier: 'free',
    icon: 'FileText',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'per month',
    defaultLimit: 10,
    configKey: 'invoiceCreation',
    active: true,
    displayOrder: 1,
  },
  {
    featureId: 'customer_management',
    name: 'Customer Management',
    displayName: 'Customer Management',
    description: 'Add and manage customer contacts with detailed profiles',
    category: 'core_business',
    tier: 'free',
    icon: 'Users',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'total customers',
    defaultLimit: 50,
    configKey: 'customerManagement',
    active: true,
    displayOrder: 2,
  },
  {
    featureId: 'product_management',
    name: 'Product Management',
    displayName: 'Product Management',
    description: 'Manage product catalog with inventory tracking',
    category: 'core_business',
    tier: 'free',
    icon: 'Package',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'total products',
    defaultLimit: 100,
    configKey: 'productManagement',
    active: true,
    displayOrder: 3,
  },
  {
    featureId: 'payment_recording',
    name: 'Payment Recording',
    displayName: 'Payment Recording',
    description: 'Record and track customer payments',
    category: 'core_business',
    tier: 'free',
    icon: 'CreditCard',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'per month',
    defaultLimit: 50,
    configKey: 'paymentRecording',
    active: true,
    displayOrder: 4,
  },
  {
    featureId: 'basic_dashboard',
    name: 'Basic Dashboard',
    displayName: 'Basic Dashboard',
    description: 'View key business metrics and statistics',
    category: 'core_business',
    tier: 'free',
    icon: 'LayoutDashboard',
    hasUsageLimit: false,
    configKey: 'basicDashboard',
    active: true,
    displayOrder: 5,
  },

  // COMMUNICATION FEATURES
  {
    featureId: 'whatsapp_business_integration',
    name: 'WhatsApp Business Integration',
    displayName: 'WhatsApp Business Integration',
    description: 'Connect WhatsApp Business account via 360Dialog',
    category: 'communication',
    tier: 'starter',
    icon: 'MessageCircle',
    hasUsageLimit: false,
    configKey: 'whatsappBusinessIntegration',
    active: true,
    displayOrder: 6,
  },
  {
    featureId: 'whatsapp_messaging',
    name: 'WhatsApp Messaging',
    displayName: 'WhatsApp Messaging',
    description: 'Send WhatsApp messages to customers',
    category: 'communication',
    tier: 'starter',
    icon: 'Send',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'per month',
    defaultLimit: 100,
    dependsOn: ['whatsapp_business_integration'],
    configKey: 'whatsappMessaging',
    planKey: 'whatsappMessages',
    active: true,
    displayOrder: 7,
  },
  {
    featureId: 'email_notifications',
    name: 'Email Notifications',
    displayName: 'Email Notifications',
    description: 'Send invoices and notifications via email',
    category: 'communication',
    tier: 'free',
    icon: 'Mail',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'per month',
    defaultLimit: 200,
    configKey: 'emailNotifications',
    planKey: 'emailsPerMonth',
    active: true,
    displayOrder: 8,
  },
  {
    featureId: 'sms_notifications',
    name: 'SMS Notifications',
    displayName: 'SMS Notifications',
    description: 'Send SMS notifications to customers',
    category: 'communication',
    tier: 'professional',
    icon: 'Smartphone',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'per month',
    defaultLimit: 50,
    configKey: 'smsNotifications',
    planKey: 'smsPerMonth',
    active: true,
    displayOrder: 9,
  },

  // ADVANCED FEATURES
  {
    featureId: 'ai_product_recognition',
    name: 'AI Product Recognition',
    displayName: 'AI Product Recognition',
    description: 'Gemini AI for product image recognition, name, description, and categorization',
    category: 'advanced',
    tier: 'professional',
    icon: 'Sparkles',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'per month',
    defaultLimit: 100,
    configKey: 'aiProductRecognition',
    planKey: 'aiFeatures',
    planType: 'boolean',
    active: true,
    displayOrder: 10,
  },
  {
    featureId: 'advanced_reporting',
    name: 'Advanced Reporting',
    displayName: 'Advanced Reporting',
    description: 'Generate detailed reports in PDF, CSV, and Excel formats',
    category: 'advanced',
    tier: 'professional',
    icon: 'FileBarChart',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'per month',
    defaultLimit: 20,
    configKey: 'advancedReporting',
    planKey: 'advancedReporting',
    planType: 'boolean',
    active: true,
    displayOrder: 11,
  },
  {
    featureId: 'advanced_analytics',
    name: 'Advanced Analytics',
    displayName: 'Advanced Analytics',
    description: 'Detailed analytics with charts and insights',
    category: 'advanced',
    tier: 'professional',
    icon: 'TrendingUp',
    hasUsageLimit: false,
    configKey: 'advancedAnalytics',
    planKey: 'advancedAnalytics',
    planType: 'boolean',
    active: true,
    displayOrder: 12,
  },
  {
    featureId: 'api_access',
    name: 'API Access',
    displayName: 'API Access',
    description: 'REST API for integrations and automation',
    category: 'integration',
    tier: 'professional',
    icon: 'Code',
    hasUsageLimit: true,
    usageLimitType: 'rate',
    usageLimitUnit: 'per hour',
    defaultLimit: 100,
    configKey: 'apiAccess',
    planKey: 'apiAccess',
    planType: 'boolean',
    active: true,
    displayOrder: 13,
  },
  {
    featureId: 'webhooks',
    name: 'Webhooks',
    displayName: 'Webhooks',
    description: 'Real-time event notifications via webhooks',
    category: 'integration',
    tier: 'enterprise',
    icon: 'Webhook',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'endpoints',
    defaultLimit: 5,
    configKey: 'webhooks',
    planKey: 'webhooks',
    planType: 'boolean',
    active: true,
    displayOrder: 14,
  },

  // COLLABORATION FEATURES
  {
    featureId: 'team_members',
    name: 'Team Members',
    displayName: 'Team Members',
    description: 'Add team members to collaborate',
    category: 'collaboration',
    tier: 'starter',
    icon: 'UserPlus',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'total team members',
    defaultLimit: 1,
    configKey: 'teamMembers',
    planKey: 'teamMembers',
    planType: 'number',
    active: true,
    displayOrder: 15,
  },
  {
    featureId: 'role_based_access',
    name: 'Role-Based Access Control',
    displayName: 'Role-Based Access Control',
    description: 'Granular permissions for team members (Owner, Admin, Manager, Staff)',
    category: 'collaboration',
    tier: 'professional',
    icon: 'Shield',
    hasUsageLimit: false,
    dependsOn: ['team_members'],
    configKey: 'roleBasedAccess',
    planKey: 'roleBasedAccess',
    planType: 'boolean',
    active: true,
    displayOrder: 16,
  },

  // CUSTOMIZATION FEATURES
  {
    featureId: 'custom_branding',
    name: 'Custom Branding',
    displayName: 'Custom Branding',
    description: 'White-label with custom logo, colors, and branding',
    category: 'customization',
    tier: 'enterprise',
    icon: 'Palette',
    hasUsageLimit: false,
    configKey: 'customBranding',
    planKey: 'customBranding',
    planType: 'boolean',
    active: true,
    displayOrder: 17,
  },
  {
    featureId: 'multi_currency',
    name: 'Multi-Currency Support',
    displayName: 'Multi-Currency Support',
    description: 'Support for multiple currencies',
    category: 'customization',
    tier: 'professional',
    icon: 'DollarSign',
    hasUsageLimit: false,
    configKey: 'multiCurrency',
    planKey: 'multiCurrency',
    planType: 'boolean',
    active: true,
    displayOrder: 18,
  },
  {
    featureId: 'dark_mode',
    name: 'Dark Mode',
    displayName: 'Dark Mode',
    description: 'Dark theme for mobile app',
    category: 'customization',
    tier: 'free',
    icon: 'Moon',
    hasUsageLimit: false,
    configKey: 'darkMode',
    planType: 'boolean',
    active: true,
    displayOrder: 19,
  },
  {
    featureId: 'custom_domains',
    name: 'Custom Domains',
    displayName: 'Custom Domains',
    description: 'Use custom domain for branded experience',
    category: 'customization',
    tier: 'enterprise',
    icon: 'Globe',
    hasUsageLimit: true,
    usageLimitType: 'count',
    usageLimitUnit: 'domains',
    defaultLimit: 1,
    configKey: 'customDomains',
    planKey: 'customDomains',
    planType: 'number',
    active: true,
    displayOrder: 20,
  },

  // SUPPORT FEATURES
  {
    featureId: 'priority_support',
    name: 'Priority Support',
    displayName: 'Priority Support',
    description: 'Dedicated priority support channel',
    category: 'support',
    tier: 'professional',
    icon: 'Headphones',
    hasUsageLimit: false,
    configKey: 'prioritySupport',
    planKey: 'prioritySupport',
    planType: 'boolean',
    active: true,
    displayOrder: 21,
  },
  {
    featureId: 'dedicated_account_manager',
    name: 'Dedicated Account Manager',
    displayName: 'Dedicated Account Manager',
    description: 'Personal account manager for enterprise support',
    category: 'support',
    tier: 'enterprise',
    icon: 'UserCheck',
    hasUsageLimit: false,
    configKey: 'dedicatedAccountManager',
    planKey: 'dedicatedAccountManager',
    planType: 'boolean',
    active: true,
    displayOrder: 22,
  },
];

async function seedFeatures() {
  console.log('🌱 Starting feature seed...\n');

  try {
    const batch = db.batch();
    let count = 0;

    for (const feature of features) {
      const featureRef = db.collection('platformFeatures').doc(feature.featureId);
      batch.set(featureRef, {
        ...feature,
        createdAt: admin.firestore.Timestamp.now(),
        updatedAt: admin.firestore.Timestamp.now(),
        updatedBy: 'system',
      });
      count++;
      console.log(`✓ ${feature.featureId} (${feature.category})`);
    }

    await batch.commit();
    console.log(`\n✅ Successfully seeded ${count} features to Firestore!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding features:', error);
    process.exit(1);
  }
}

seedFeatures();
